//! Offline synthesis of IMPACT's 3 embedded PCM transient variants (SPECS: "3 embedded
//! PCM transients (generated offline)"). No external audio files, ever — the samples are
//! synthesized here at build time and emitted as `const [f32; N]` arrays into
//! `$OUT_DIR/transients.rs`, which `dsp.rs` `include!`s. Each variant is a short click
//! rendered at 48 kHz, Hann-windowed at both ends so playback from index 0 starts and ends
//! at exactly zero (no onset/offset step — critical for the retrigger declick done-bar).

use std::env;
use std::f32::consts::TAU;
use std::fs;
use std::path::Path;

/// Tiny deterministic LCG so the generated transients are reproducible across builds.
struct Lcg(u32);
impl Lcg {
    fn next_bipolar(&mut self) -> f32 {
        // Numerical Recipes LCG.
        self.0 = self.0.wrapping_mul(1_664_525).wrapping_add(1_013_904_223);
        (self.0 >> 8) as f32 / (1u32 << 24) as f32 * 2.0 - 1.0
    }
}

/// A one-pole state-variable bandpass (matches suite_core::dsp::Svf topology) so the
/// build-time click timbre lines up with the runtime noise-click band.
struct Svf {
    ic1: f32,
    ic2: f32,
    g: f32,
    k: f32,
    a1: f32,
    a2: f32,
    a3: f32,
}
impl Svf {
    fn new(fc: f32, q: f32, sr: f32) -> Self {
        let g = (std::f32::consts::PI * fc / sr).tan();
        let k = 1.0 / q;
        let a1 = 1.0 / (1.0 + g * (g + k));
        Self { ic1: 0.0, ic2: 0.0, g, k, a1, a2: g * a1, a3: g * (g * a1) }
    }
    fn bp(&mut self, x: f32) -> f32 {
        let v3 = x - self.ic2;
        let v1 = self.a1 * self.ic1 + self.a2 * v3;
        let v2 = self.ic2 + self.a2 * self.ic1 + self.a3 * v3;
        self.ic1 = 2.0 * v1 - self.ic1;
        self.ic2 = 2.0 * v2 - self.ic2;
        v1
    }
}

/// Raised-cosine (Hann) fade over `fade` samples at each end; guarantees s[0] == s[N-1] == 0.
fn window(buf: &mut [f32], fade: usize) {
    let n = buf.len();
    let fade = fade.min(n / 2).max(1);
    for i in 0..fade {
        let w = 0.5 - 0.5 * (std::f32::consts::PI * i as f32 / fade as f32).cos();
        buf[i] *= w;
        buf[n - 1 - i] *= w;
    }
}

/// Normalize to a target absolute peak.
fn normalize(buf: &mut [f32], peak: f32) {
    let m = buf.iter().fold(0.0f32, |a, &v| a.max(v.abs()));
    if m > 1e-9 {
        let g = peak / m;
        for v in buf.iter_mut() {
            *v *= g;
        }
    }
}

/// Variant 0 "Tick": very short bright click — white noise through a high bandpass, fast decay.
fn tick(sr: f32) -> Vec<f32> {
    let n = (sr * 0.0035) as usize; // ~3.5 ms
    let mut rng = Lcg(0x1234_5678);
    let mut bp = Svf::new(6500.0, 3.0, sr);
    let mut out = vec![0.0f32; n];
    for (i, o) in out.iter_mut().enumerate() {
        let t = i as f32 / sr;
        let env = (-t / 0.0008).exp();
        *o = bp.bp(rng.next_bipolar()) * env;
    }
    window(&mut out, (sr * 0.0004) as usize);
    normalize(&mut out, 1.0);
    out
}

/// Variant 1 "Snap": mid transient — noise band ~2 kHz plus a fast decaying 1.6 kHz tone.
fn snap(sr: f32) -> Vec<f32> {
    let n = (sr * 0.006) as usize; // ~6 ms
    let mut rng = Lcg(0x0BAD_F00D);
    let mut bp = Svf::new(2200.0, 1.5, sr);
    let mut out = vec![0.0f32; n];
    for (i, o) in out.iter_mut().enumerate() {
        let t = i as f32 / sr;
        let noise = bp.bp(rng.next_bipolar()) * (-t / 0.0015).exp();
        let tone = (TAU * 1600.0 * t).sin() * (-t / 0.0022).exp();
        *o = 0.6 * noise + 0.5 * tone;
    }
    window(&mut out, (sr * 0.0006) as usize);
    normalize(&mut out, 1.0);
    out
}

/// Variant 2 "Knock": woody low-mid transient — damped 420 Hz sine + a touch of noise body.
fn knock(sr: f32) -> Vec<f32> {
    let n = (sr * 0.010) as usize; // ~10 ms
    let mut rng = Lcg(0xC0FF_EE11);
    let mut bp = Svf::new(700.0, 1.0, sr);
    let mut out = vec![0.0f32; n];
    for (i, o) in out.iter_mut().enumerate() {
        let t = i as f32 / sr;
        let body = (TAU * 420.0 * t).sin() * (-t / 0.0035).exp();
        let noise = bp.bp(rng.next_bipolar()) * (-t / 0.0012).exp();
        *o = 0.8 * body + 0.3 * noise;
    }
    window(&mut out, (sr * 0.0009) as usize);
    normalize(&mut out, 1.0);
    out
}

fn emit(name: &str, buf: &[f32], out: &mut String) {
    out.push_str(&format!("pub const {name}: [f32; {}] = [", buf.len()));
    for (i, v) in buf.iter().enumerate() {
        if i % 8 == 0 {
            out.push_str("\n    ");
        }
        out.push_str(&format!("{v:.7}, "));
    }
    out.push_str("\n];\n\n");
}

fn main() {
    let sr = 48_000.0f32;
    let mut src = String::from(
        "// GENERATED by build.rs — IMPACT embedded PCM transients (48 kHz, windowed). Do not edit.\n\n",
    );
    emit("TRANSIENT_TICK", &tick(sr), &mut src);
    emit("TRANSIENT_SNAP", &snap(sr), &mut src);
    emit("TRANSIENT_KNOCK", &knock(sr), &mut src);
    src.push_str("pub const TRANSIENT_SR: f32 = 48_000.0;\n");
    src.push_str(
        "pub const TRANSIENTS: [&[f32]; 3] = [&TRANSIENT_TICK, &TRANSIENT_SNAP, &TRANSIENT_KNOCK];\n",
    );

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("transients.rs");
    fs::write(&dest, src).unwrap();
    println!("cargo:rerun-if-changed=build.rs");
}
